name: gonswapGPT
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=3.7.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cryptography=41.0.7
  - dataclasses-json=0.6.3
  - exceptiongroup=1.2.0
  - frozenlist=1.4.0
  - google-api-core=2.15.0
  - google-auth=2.25.2
  - googleapis-common-protos=1.62.0
  - greenlet=3.0.2
  - idna=3.6
  - iniconfig=2.0.0
  - jsonpatch=1.33
  - jsonpointer=2.4
  - langchain=0.0.340
  - langsmith=0.0.69
  - ld_impl_linux-64=2.40
  - libabseil=20230802.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libprotobuf=4.24.4
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - marshmallow=3.20.1
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nomkl=1.0
  - numexpr=2.8.7
  - numpy=1.26.2
  - openapi-schema-pydantic=1.2.4
  - openssl=3.2.0
  - packaging=23.2
  - pip=23.3.1
  - pluggy=1.3.0
  - protobuf=4.24.4
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pydantic=2.5.2
  - pydantic-core=2.14.5
  - pyopenssl=23.3.0
  - pysocks=1.7.1
  - pytest=7.4.3
  - pytest-subtests=0.11.0
  - python=3.11.6
  - python_abi=3.11
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - rsa=4.9
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.23
  - tenacity=8.2.3
  - tk=8.6.13
  - tomli=2.0.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_inspect=0.9.0
  - tzdata=2023c
  - urllib3=2.1.0
  - wheel=0.42.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - pip:
      - bitarray==2.8.5
      - click==8.1.7
      - cytoolz==0.12.2
      - distro==1.8.0
      - eth-abi==4.2.1
      - eth-account==0.10.0
      - eth-hash==0.5.2
      - eth-keyfile==0.7.0
      - eth-keys==0.4.0
      - eth-rlp==1.0.0
      - eth-typing==3.5.2
      - eth-utils==2.3.1
      - fastapi==0.105.0
      - h11==0.14.0
      - hexbytes==0.3.1
      - hiredis==2.2.3
      - httpcore==1.0.2
      - httpx==0.25.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - lru-dict==1.2.0
      - mypy==1.7.1
      - nest-asyncio==1.5.8
      - openai==1.3.8
      - parsimonious==0.9.0
      - pycryptodome==3.19.0
      - pyunormalize==15.1.0
      - redis==5.0.1
      - referencing==0.32.0
      - regex==2023.10.3
      - rlp==4.0.0
      - rpds-py==0.13.2
      - starlette==0.27.0
      - toolz==0.12.0
      - tqdm==4.66.1
      - uvicorn==0.24.0.post1
      - web3==6.12.0
      - websockets==12.0
