name: tradingGPT
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohttp=3.9.0
  - aiosignal=1.3.1
  - anyio=3.7.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cryptography=41.0.3
  - dataclasses-json=0.6.3
  - exceptiongroup=1.2.0
  - frozenlist=1.4.0
  - google-api-core=2.14.0
  - google-auth=2.24.0
  - googleapis-common-protos=1.61.0
  - greenlet=2.0.1
  - idna=3.6
  - iniconfig=2.0.0
  - intel-openmp=2023.1.0
  - jsonpatch=1.33
  - jsonpointer=2.0
  - langchain=0.0.340
  - langsmith=0.0.69
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - marshmallow=3.20.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openapi-schema-pydantic=1.2.4
  - openssl=3.0.12
  - packaging=23.2
  - pip=23.3.1
  - pluggy=1.3.0
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pyopenssl=23.2.0
  - pytest=7.4.3
  - pytest-subtests=0.11.0
  - python=3.11.5
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - rsa=4.9
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.21
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tenacity=8.2.3
  - tk=8.6.12
  - tomli=2.0.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_inspect=0.9.0
  - tzdata=2023c
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - pip:
      - argparse==1.4.0
      - bitarray==2.8.4
      - click==8.1.7
      - cytoolz==0.12.2
      - distro==1.8.0
      - eth-abi==4.2.1
      - eth-account==0.10.0
      - eth-hash==0.5.2
      - eth-keyfile==0.6.1
      - eth-keys==0.4.0
      - eth-rlp==0.3.0
      - eth-typing==3.5.2
      - eth-utils==2.3.1
      - fastapi==0.104.1
      - h11==0.14.0
      - hexbytes==0.3.1
      - hiredis==2.2.3
      - httpcore==1.0.2
      - httpx==0.25.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - lru-dict==1.2.0
      - nest-asyncio==1.5.8
      - openai==1.3.7
      - parsimonious==0.9.0
      - protobuf==4.25.1
      - pycryptodome==3.19.0
      - pyunormalize==15.1.0
      - redis==5.0.1
      - referencing==0.31.1
      - regex==2023.10.3
      - rlp==3.0.0
      - rpds-py==0.13.2
      - starlette==0.27.0
      - toolz==0.12.0
      - tqdm==4.66.1
      - uvicorn==0.24.0.post1
      - web3==6.11.4
      - websockets==12.0
